// flow-typed signature: 7b43d9fa2e94b77aa2a395d96adbc4bb
// flow-typed version: <<STUB>>/fetch-ie8_v^1.5.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-ie8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-ie8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-ie8/fetch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-ie8/fetch.js' {
  declare module.exports: $Exports<'fetch-ie8/fetch'>;
}
