// flow-typed signature: 1b565e3ffe8db91f05e21ad5d93789b7
// flow-typed version: <<STUB>>/inject-loader_v^3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inject-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inject-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inject-loader/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inject-loader/dist/index.js' {
  declare module.exports: $Exports<'inject-loader/dist/index'>;
}
